"""Test add favorite.

Revision ID: 1fece2fbe32b
Revises: 3c49d7378623
Create Date: 2013-09-14 08:51:46.492559

"""

# revision identifiers, used by Alembic.
revision = '1fece2fbe32b'
down_revision = '3c49d7378623'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stuff', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    ### end Alembic commands ###
