"""Test add favorite.

Revision ID: 24e57af7da60
Revises: 1fece2fbe32b
Create Date: 2013-09-14 08:53:13.139402

"""

# revision identifiers, used by Alembic.
revision = '24e57af7da60'
down_revision = '1fece2fbe32b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'favorite')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'favorite',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('favorite_id_seq'::regclass)", nullable=False),
    sa.Column(u'stuff', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'favorite_pkey')
    )
    ### end Alembic commands ###
